ln -s `pwd`/snap.sh ${HOME}/bin/snap-bottom
ln -s `pwd`/snap.sh ${HOME}/bin/snap-bottom-left
ln -s `pwd`/snap.sh ${HOME}/bin/snap-bottom-right
ln -s `pwd`/snap.sh ${HOME}/bin/snap-full
ln -s `pwd`/snap.sh ${HOME}/bin/snap-full-height
ln -s `pwd`/snap.sh ${HOME}/bin/snap-full-width
ln -s `pwd`/snap.sh ${HOME}/bin/snap-left
ln -s `pwd`/snap.sh ${HOME}/bin/snap-max
ln -s `pwd`/snap.sh ${HOME}/bin/snap-min
ln -s `pwd`/snap.sh ${HOME}/bin/snap-right
ln -s `pwd`/snap.sh ${HOME}/bin/snap-top
ln -s `pwd`/snap.sh ${HOME}/bin/snap-top-left
ln -s `pwd`/snap.sh ${HOME}/bin/snap-top-right
