ln -s snap.sh snap
ln -s snap snap-bottom
ln -s snap snap-bottom-left
ln -s snap snap-bottom-right
ln -s snap snap-full
ln -s snap snap-full-height
ln -s snap snap-full-width
ln -s snap snap-left
ln -s snap snap-max
ln -s snap snap-min
ln -s snap snap-right
ln -s snap snap-top
ln -s snap snap-top-left
ln -s snap snap-top-right
